// Curated autocomplete candidates for the math field. Every `name` is a
// real LatexCmds entry in the vendored MathQuill build — inserting
// `\${name}` via mq.cmd() or the latex command input always resolves.
// Order is the ranking order: structure and common operators first.
import { NOTATION } from '../compile/notation';

export interface CompletionItem {
  /** Command name without the backslash — what gets typed and inserted. */
  name: string;
  /** Short description for menus. */
  hint?: string;
  /** LaTeX rendered as the item's preview. Defaults to `\${name}`. */
  preview?: string;
}

// Palette items a notation entry carries itself — the item is generated
// from the registry so the insertion alias stays beside the notation it
// expands to; ordering stays in this list's hands via placement.
const fromRegistry = (name: string): CompletionItem => {
  const item = NOTATION.find((n) => n.completion?.name === name)?.completion;
  if (item === undefined)
    throw new Error(`no registry completion named ${name}`);
  return item;
};

export const COMPLETIONS: CompletionItem[] = [
  { name: 'frac', hint: 'fraction', preview: '\\frac{a}{b}' },
  { name: 'sqrt', hint: 'square root', preview: '\\sqrt{x}' },
  { name: 'nthroot', hint: 'nth root', preview: '\\sqrt[n]{x}' },
  { name: 'int', hint: 'definite integral', preview: '\\int_{a}^{b}' },
  { name: 'iint', hint: 'double integral (boundless)', preview: '\\iint' },
  // `\int` always renders bound blocks (empty = grey squares) — the
  // boundless `\antid` leaf renders the same ∫ glyph without them.
  { name: 'antid', hint: 'antiderivative', preview: '\\antid f(x)\\,dx' },
  { name: 'iiint', hint: 'triple integral', preview: '\\iiint' },
  { name: 'sum', hint: 'summation', preview: '\\sum_{k=1}^{n}' },
  { name: 'prod', hint: 'product', preview: '\\prod_{k=1}^{n}' },
  { name: 'lim', hint: 'limit', preview: '\\lim_{x\\to 0}' },
  // `\D` and `\gradient` are insertion aliases — they expand to
  // `\text{D}` and `\nabla`; the items come from their registry
  // entries. `D` must outrank 'derivative' — Enter accepts the first
  // prefix match, and a typed `\D` means the total derivative.
  fromRegistry('D'),
  {
    name: 'derivative',
    hint: 'd/dx operator',
    preview: '\\frac{d }{d x}',
  },
  { name: 'partial', hint: 'partial derivative', preview: '\\partial' },
  fromRegistry('gradient'),
  { name: 'binom', hint: 'binomial coefficient', preview: '\\binom{n}{k}' },
  { name: 'pmatrix', hint: 'matrix', preview: '\\pmatrix{a&b\\\\c&d}' },
  { name: 'begin', hint: 'environment (pmatrix, cases, …)' },
  { name: 'def', hint: 'function definition', preview: '\\text{def} ' },
  { name: 'plot', hint: 'plot a function', preview: '\\text{plot} ' },
  { name: 'python', hint: 'inline Python code', preview: '\\python{x = 1}' },
  // `\tr` is an insertion alias — it expands to `\mathrm{tr}`; the item
  // comes from the trace registry entry.
  fromRegistry('tr'),
  { name: 'matrix', hint: 'matrix grid', preview: '\\begin{matrix}a&b\\\\c&d\\end{matrix}' },
  { name: 'bmatrix', hint: '[ ] matrix', preview: '\\begin{bmatrix}a&b\\\\c&d\\end{bmatrix}' },
  { name: 'Bmatrix', hint: '{ } matrix', preview: '\\begin{Bmatrix}a&b\\\\c&d\\end{Bmatrix}' },
  { name: 'vmatrix', hint: '| | matrix', preview: '\\begin{vmatrix}a&b\\\\c&d\\end{vmatrix}' },
  { name: 'Vmatrix', hint: '‖ ‖ matrix', preview: '\\begin{Vmatrix}a&b\\\\c&d\\end{Vmatrix}' },
  { name: 'smallmatrix', hint: 'small matrix', preview: '\\begin{smallmatrix}a&b\\\\c&d\\end{smallmatrix}' },
  { name: 'cases', hint: 'piecewise cases', preview: '\\begin{cases}a&b\\\\c&d\\end{cases}' },
  { name: 'aligned', hint: 'aligned equations', preview: '\\begin{aligned}a&=b\\\\c&=d\\end{aligned}' },
  { name: 'align', hint: 'aligned equations', preview: '\\begin{aligned}a&=b\\\\c&=d\\end{aligned}' },
  { name: 'split', hint: 'aligned equations', preview: '\\begin{aligned}a&=b\\\\c&=d\\end{aligned}' },
  { name: 'eqnarray', hint: 'aligned equations', preview: '\\begin{aligned}a&=b\\\\c&=d\\end{aligned}' },
  { name: 'gathered', hint: 'single-column rows', preview: '\\begin{gathered}a\\\\b\\end{gathered}' },
  { name: 'gather', hint: 'single-column rows', preview: '\\begin{gathered}a\\\\b\\end{gathered}' },
  { name: 'multline', hint: 'single-column rows', preview: '\\begin{gathered}a\\\\b\\end{gathered}' },
  { name: 'flalign', hint: 'single-column rows', preview: '\\begin{gathered}a\\\\b\\end{gathered}' },
  { name: 'equation', hint: 'single-column rows', preview: '\\begin{gathered}a\\end{gathered}' },
  { name: 'displaylines', hint: 'multi-line rows', preview: '\\displaylines{a\\\\b}' },
  { name: 'array', hint: 'spec-arg grid {cc}', preview: '\\begin{array}{cc}a&b\\\\c&d\\end{array}' },
  { name: 'subarray', hint: 'spec-arg sub stack', preview: '\\begin{subarray}{c}a\\\\b\\end{subarray}' },
  { name: 'tabular', hint: 'spec-arg table {cc}', preview: '\\begin{tabular}{cc}a&b\\\\c&d\\end{tabular}' },
  { name: 'alignat', hint: 'spec-arg aligned {n}', preview: '\\begin{alignat}{2}a&=b\\\\c&=d\\end{alignat}' },
  { name: 'alignedat', hint: 'spec-arg aligned {n}', preview: '\\begin{alignedat}{2}a&=b\\\\c&=d\\end{alignedat}' },
  { name: 'substack', hint: 'stacked bound', preview: '\\substack{a\\\\b}' },
  { name: 'sin' },
  { name: 'cos' },
  { name: 'tan' },
  { name: 'sec' },
  { name: 'csc' },
  { name: 'cot' },
  { name: 'arcsin' },
  { name: 'arccos' },
  { name: 'arctan' },
  { name: 'sinh' },
  { name: 'cosh' },
  { name: 'tanh' },
  { name: 'ln' },
  { name: 'log' },
  { name: 'exp' },
  { name: 'min' },
  { name: 'max' },
  { name: 'gcd' },
  { name: 'det', hint: 'determinant' },
  { name: 'inf', hint: 'infimum' },
  { name: 'sup', hint: 'supremum' },
  { name: 'alpha' },
  { name: 'beta' },
  { name: 'gamma' },
  { name: 'delta' },
  { name: 'epsilon' },
  { name: 'varepsilon' },
  { name: 'zeta' },
  { name: 'eta' },
  { name: 'theta' },
  { name: 'vartheta' },
  { name: 'lambda' },
  { name: 'mu' },
  { name: 'nu' },
  { name: 'xi' },
  { name: 'pi' },
  { name: 'rho' },
  { name: 'sigma' },
  { name: 'tau' },
  { name: 'phi' },
  { name: 'varphi' },
  { name: 'chi' },
  { name: 'psi' },
  { name: 'omega' },
  { name: 'Gamma' },
  { name: 'Delta' },
  { name: 'Theta' },
  { name: 'Lambda' },
  { name: 'Sigma' },
  { name: 'Phi' },
  { name: 'Psi' },
  { name: 'Omega' },
  { name: 'infty', hint: 'infinity' },
  { name: 'nabla', hint: 'gradient' },
  { name: 'ell' },
  { name: 'hbar', hint: 'reduced Planck constant' },
  { name: 'aleph' },
  { name: 'leq', hint: '≤' },
  { name: 'geq', hint: '≥' },
  { name: 'neq', hint: '≠' },
  { name: 'approx', hint: '≈' },
  { name: 'equiv', hint: '≡' },
  { name: 'propto', hint: '∝' },
  { name: 'cong', hint: '≅' },
  { name: 'sim', hint: '∼' },
  { name: 'll', hint: '≪' },
  { name: 'gg', hint: '≫' },
  { name: 'to', hint: '→' },
  { name: 'mapsto', hint: '↦' },
  { name: 'rightarrow', hint: '→' },
  { name: 'leftarrow', hint: '←' },
  { name: 'Rightarrow', hint: '⇒' },
  { name: 'leftrightarrow', hint: '↔' },
  { name: 'implies', hint: '⇒' },
  { name: 'iff', hint: '⇔' },
  { name: 'pm', hint: '±' },
  { name: 'mp', hint: '∓' },
  { name: 'times', hint: '×' },
  { name: 'div', hint: '÷' },
  { name: 'cdot', hint: '·' },
  { name: 'circ', hint: '∘' },
  { name: 'bullet', hint: '•' },
  { name: 'wedge', hint: '∧' },
  { name: 'vee', hint: '∨' },
  { name: 'oplus', hint: '⊕' },
  { name: 'otimes', hint: '⊗' },
  { name: 'cup', hint: 'union ∪' },
  { name: 'cap', hint: 'intersection ∩' },
  { name: 'setminus', hint: '∖' },
  { name: 'in', hint: '∈' },
  { name: 'notin', hint: '∉' },
  { name: 'ni', hint: '∋' },
  { name: 'subset', hint: '⊂' },
  { name: 'supset', hint: '⊃' },
  { name: 'subseteq', hint: '⊆' },
  { name: 'supseteq', hint: '⊇' },
  { name: 'emptyset', hint: '∅' },
  { name: 'varnothing', hint: '∅' },
  { name: 'forall', hint: '∀' },
  { name: 'exists', hint: '∃' },
  { name: 'nexists', hint: '∄' },
  { name: 'mid', hint: 'such that ∣' },
  { name: 'parallel', hint: '∥' },
  { name: 'perp', hint: '⊥' },
  { name: 'Reals', hint: 'ℝ' },
  { name: 'Naturals', hint: 'ℕ' },
  { name: 'Integers', hint: 'ℤ' },
  { name: 'Rationals', hint: 'ℚ' },
  { name: 'Complexes', hint: 'ℂ' },
  { name: 'mathbb', hint: 'blackboard bold', preview: '\\mathbb{R}' },
  { name: 'mathcal', hint: 'calligraphic', preview: '\\mathcal{F}' },
  { name: 'mathbf', hint: 'bold', preview: '\\mathbf{v}' },
  { name: 'mathrm', hint: 'upright (roman) text', preview: '\\mathrm{kg}' },
  { name: 'text', hint: 'text mode', preview: '\\text{and}' },
  { name: 'hat', hint: 'accent', preview: '\\hat{x}' },
  { name: 'bar', hint: 'accent', preview: '\\bar{x}' },
  { name: 'vec', hint: 'vector arrow', preview: '\\vec{v}' },
  { name: 'dot', hint: 'accent', preview: '\\dot{x}' },
  { name: 'ddot', hint: 'accent', preview: '\\ddot{x}' },
  { name: 'tilde', hint: 'accent', preview: '\\tilde{x}' },
  { name: 'overline', preview: '\\overline{AB}' },
  { name: 'underline', preview: '\\underline{u}' },
  { name: 'overset', hint: 'stack above', preview: '\\overset{a}{b}' },
  { name: 'lfloor', hint: '⌊' },
  { name: 'rfloor', hint: '⌋' },
  { name: 'lceil', hint: '⌈' },
  { name: 'rceil', hint: '⌉' },
  { name: 'langle', hint: '⟨' },
  { name: 'rangle', hint: '⟩' },
  { name: 'cdots', hint: '⋯' },
  { name: 'ldots', hint: '…' },
  { name: 'vdots', hint: '⋮' },
  { name: 'ddots', hint: '⋱' },
  { name: 'therefore', hint: '∴' },
  { name: 'because', hint: '∵' },
  { name: 'angle', hint: '∠' },
  { name: 'degree', hint: '°' },
  { name: 'prime', hint: '′' },
  { name: 'quad', hint: 'wide space' },
  { name: 'qquad', hint: 'wider space' },
];

// Prefix match in catalog order — the list itself is the ranking (most
// common commands first), so 'i' leads with int, not the shortest name.
export function matchCompletions(
  prefix: string,
  limit = 8,
): CompletionItem[] {
  const p = prefix.toLowerCase();
  return COMPLETIONS.filter((c) =>
    c.name.toLowerCase().startsWith(p),
  ).slice(0, limit);
}
