// Curated autocomplete candidates for the math field. Every `name` is a
// real LatexCmds entry in the vendored MathQuill build — inserting
// `\${name}` via mq.cmd() or the latex command input always resolves.
// Order is the ranking order: structure and common operators first.
export interface CompletionItem {
  /** Command name without the backslash — what gets typed and inserted. */
  name: string;
  /** Short description for menus. */
  hint?: string;
  /** LaTeX rendered as the item's preview. Defaults to `\${name}`. */
  preview?: string;
}

export const COMPLETIONS: CompletionItem[] = [
  { name: 'frac', hint: 'fraction', preview: '\\frac{a}{b}' },
  { name: 'sqrt', hint: 'square root', preview: '\\sqrt{x}' },
  { name: 'nthroot', hint: 'nth root', preview: '\\sqrt[n]{x}' },
  { name: 'int', hint: 'definite integral', preview: '\\int_{a}^{b}' },
  { name: 'iint', hint: 'indefinite integral', preview: '\\iint' },
  { name: 'antid', hint: 'antiderivative', preview: '\\int' },
  { name: 'iiint', hint: 'triple integral', preview: '\\iiint' },
  { name: 'sum', hint: 'summation', preview: '\\sum_{k=1}^{n}' },
  { name: 'prod', hint: 'product', preview: '\\prod_{k=1}^{n}' },
  { name: 'lim', hint: 'limit', preview: '\\lim_{x\\to 0}' },
  {
    name: 'derivative',
    hint: 'd/dx operator',
    preview: '\\frac{d }{d x}',
  },
  { name: 'partial', hint: 'partial derivative', preview: '\\partial' },
  { name: 'binom', hint: 'binomial coefficient', preview: '\\binom{n}{k}' },
  { name: 'pmatrix', hint: 'matrix', preview: '\\pmatrix{a&b\\\\c&d}' },
  { name: 'begin', hint: 'environment (pmatrix, cases, …)' },
  { name: 'sin' },
  { name: 'cos' },
  { name: 'tan' },
  { name: 'sec' },
  { name: 'csc' },
  { name: 'cot' },
  { name: 'arcsin' },
  { name: 'arccos' },
  { name: 'arctan' },
  { name: 'sinh' },
  { name: 'cosh' },
  { name: 'tanh' },
  { name: 'ln' },
  { name: 'log' },
  { name: 'exp' },
  { name: 'min' },
  { name: 'max' },
  { name: 'gcd' },
  { name: 'det', hint: 'determinant' },
  { name: 'inf', hint: 'infimum' },
  { name: 'sup', hint: 'supremum' },
  { name: 'alpha' },
  { name: 'beta' },
  { name: 'gamma' },
  { name: 'delta' },
  { name: 'epsilon' },
  { name: 'varepsilon' },
  { name: 'zeta' },
  { name: 'eta' },
  { name: 'theta' },
  { name: 'vartheta' },
  { name: 'lambda' },
  { name: 'mu' },
  { name: 'nu' },
  { name: 'xi' },
  { name: 'pi' },
  { name: 'rho' },
  { name: 'sigma' },
  { name: 'tau' },
  { name: 'phi' },
  { name: 'varphi' },
  { name: 'chi' },
  { name: 'psi' },
  { name: 'omega' },
  { name: 'Gamma' },
  { name: 'Delta' },
  { name: 'Theta' },
  { name: 'Lambda' },
  { name: 'Sigma' },
  { name: 'Phi' },
  { name: 'Psi' },
  { name: 'Omega' },
  { name: 'infty', hint: 'infinity' },
  { name: 'nabla', hint: 'gradient' },
  { name: 'ell' },
  { name: 'hbar', hint: 'reduced Planck constant' },
  { name: 'aleph' },
  { name: 'leq', hint: '≤' },
  { name: 'geq', hint: '≥' },
  { name: 'neq', hint: '≠' },
  { name: 'approx', hint: '≈' },
  { name: 'equiv', hint: '≡' },
  { name: 'propto', hint: '∝' },
  { name: 'cong', hint: '≅' },
  { name: 'sim', hint: '∼' },
  { name: 'll', hint: '≪' },
  { name: 'gg', hint: '≫' },
  { name: 'to', hint: '→' },
  { name: 'mapsto', hint: '↦' },
  { name: 'rightarrow', hint: '→' },
  { name: 'leftarrow', hint: '←' },
  { name: 'Rightarrow', hint: '⇒' },
  { name: 'leftrightarrow', hint: '↔' },
  { name: 'implies', hint: '⇒' },
  { name: 'iff', hint: '⇔' },
  { name: 'pm', hint: '±' },
  { name: 'mp', hint: '∓' },
  { name: 'times', hint: '×' },
  { name: 'div', hint: '÷' },
  { name: 'cdot', hint: '·' },
  { name: 'circ', hint: '∘' },
  { name: 'bullet', hint: '•' },
  { name: 'wedge', hint: '∧' },
  { name: 'vee', hint: '∨' },
  { name: 'oplus', hint: '⊕' },
  { name: 'otimes', hint: '⊗' },
  { name: 'cup', hint: 'union ∪' },
  { name: 'cap', hint: 'intersection ∩' },
  { name: 'setminus', hint: '∖' },
  { name: 'in', hint: '∈' },
  { name: 'notin', hint: '∉' },
  { name: 'ni', hint: '∋' },
  { name: 'subset', hint: '⊂' },
  { name: 'supset', hint: '⊃' },
  { name: 'subseteq', hint: '⊆' },
  { name: 'supseteq', hint: '⊇' },
  { name: 'emptyset', hint: '∅' },
  { name: 'varnothing', hint: '∅' },
  { name: 'forall', hint: '∀' },
  { name: 'exists', hint: '∃' },
  { name: 'nexists', hint: '∄' },
  { name: 'mid', hint: 'such that ∣' },
  { name: 'parallel', hint: '∥' },
  { name: 'perp', hint: '⊥' },
  { name: 'Reals', hint: 'ℝ' },
  { name: 'Naturals', hint: 'ℕ' },
  { name: 'Integers', hint: 'ℤ' },
  { name: 'Rationals', hint: 'ℚ' },
  { name: 'Complexes', hint: 'ℂ' },
  { name: 'mathbb', hint: 'blackboard bold', preview: '\\mathbb{R}' },
  { name: 'mathcal', hint: 'calligraphic', preview: '\\mathcal{F}' },
  { name: 'mathbf', hint: 'bold', preview: '\\mathbf{v}' },
  { name: 'text', hint: 'text mode', preview: '\\text{and}' },
  { name: 'hat', hint: 'accent', preview: '\\hat{x}' },
  { name: 'bar', hint: 'accent', preview: '\\bar{x}' },
  { name: 'vec', hint: 'vector arrow', preview: '\\vec{v}' },
  { name: 'dot', hint: 'accent', preview: '\\dot{x}' },
  { name: 'ddot', hint: 'accent', preview: '\\ddot{x}' },
  { name: 'tilde', hint: 'accent', preview: '\\tilde{x}' },
  { name: 'overline', preview: '\\overline{AB}' },
  { name: 'underline', preview: '\\underline{u}' },
  { name: 'overset', hint: 'stack above', preview: '\\overset{a}{b}' },
  { name: 'lfloor', hint: '⌊' },
  { name: 'rfloor', hint: '⌋' },
  { name: 'lceil', hint: '⌈' },
  { name: 'rceil', hint: '⌉' },
  { name: 'langle', hint: '⟨' },
  { name: 'rangle', hint: '⟩' },
  { name: 'cdots', hint: '⋯' },
  { name: 'ldots', hint: '…' },
  { name: 'vdots', hint: '⋮' },
  { name: 'ddots', hint: '⋱' },
  { name: 'therefore', hint: '∴' },
  { name: 'because', hint: '∵' },
  { name: 'angle', hint: '∠' },
  { name: 'degree', hint: '°' },
  { name: 'prime', hint: '′' },
  { name: 'quad', hint: 'wide space' },
  { name: 'qquad', hint: 'wider space' },
];

// Prefix match in catalog order — the list itself is the ranking (most
// common commands first), so 'i' leads with int, not the shortest name.
export function matchCompletions(
  prefix: string,
  limit = 8,
): CompletionItem[] {
  const p = prefix.toLowerCase();
  return COMPLETIONS.filter((c) =>
    c.name.toLowerCase().startsWith(p),
  ).slice(0, limit);
}
