// Catalog for the \… autocomplete dropdown. `cmd` is the exact text of
// the command input (what follows the backslash); entries containing
// '{' — the \begin{env} family — need no trailing Enter (the '}' builds
// the environment), hence `accept: false`. `preview` is rendered via
// StaticMath so the glyph is visible before committing.
export interface CatalogEntry {
  cmd: string;
  title: string;
  preview: string;
  kw?: string;
  accept?: boolean;
}

export const COMMAND_CATALOG: CatalogEntry[] = [
  // Structures (accept -> template leaves the caret in the first slot)
  { cmd: 'int', title: 'definite integral', preview: '\\int_{a}^{b}', kw: 'integral bounds' },
  { cmd: 'antid', title: 'indefinite integral', preview: '\\int', kw: 'integral antiderivative' },
  { cmd: 'iint', title: 'double integral', preview: '\\iint', kw: 'integral area' },
  { cmd: 'iiint', title: 'triple integral', preview: '\\iiint', kw: 'integral volume' },
  { cmd: 'oiint', title: 'closed surface integral', preview: '\\oiint', kw: 'integral flux surface' },
  { cmd: 'intop', title: 'integral operator', preview: '\\intop', kw: 'integral' },
  { cmd: 'sum', title: 'summation', preview: '\\sum_{i=0}^{n}', kw: 'sigma series' },
  { cmd: 'prod', title: 'product', preview: '\\prod_{i=0}^{n}', kw: 'pi' },
  { cmd: 'lim', title: 'limit', preview: '\\lim_{x\\to0}', kw: 'tends' },
  { cmd: 'limsup', title: 'limit superior', preview: '\\limsup', kw: 'limit' },
  { cmd: 'liminf', title: 'limit inferior', preview: '\\liminf', kw: 'limit' },
  { cmd: 'derivative', title: 'd/dx derivative', preview: '\\frac{d}{dx}', kw: 'diff' },
  { cmd: 'frac', title: 'fraction', preview: '\\frac{a}{b}', kw: 'divide over' },
  { cmd: 'sqrt', title: 'square root', preview: '\\sqrt{x}', kw: 'radical' },
  { cmd: 'nthroot', title: 'nth root', preview: '\\sqrt[n]{x}', kw: 'radical root' },
  { cmd: 'binom', title: 'binomial coefficient', preview: '\\binom{n}{k}', kw: 'choose' },
  { cmd: 'substack', title: 'stacked subscript lines', preview: '\\substack{a\\\\b}', kw: 'stack' },
  { cmd: 'begin{pmatrix}', title: '( ) matrix', preview: '\\begin{pmatrix}a&b\\\\c&d\\end{pmatrix}', kw: 'matrix grid', accept: false },
  { cmd: 'begin{bmatrix}', title: '[ ] matrix', preview: '\\begin{bmatrix}a&b\\\\c&d\\end{bmatrix}', kw: 'matrix grid', accept: false },
  { cmd: 'begin{Bmatrix}', title: '{ } matrix', preview: '\\begin{Bmatrix}a&b\\\\c&d\\end{Bmatrix}', kw: 'matrix grid braces', accept: false },
  { cmd: 'begin{vmatrix}', title: '| | determinant', preview: '\\begin{vmatrix}a&b\\\\c&d\\end{vmatrix}', kw: 'determinant matrix', accept: false },
  { cmd: 'begin{Vmatrix}', title: '‖ ‖ matrix', preview: '\\begin{Vmatrix}a&b\\\\c&d\\end{Vmatrix}', kw: 'matrix norm', accept: false },
  { cmd: 'begin{matrix}', title: 'bare matrix', preview: '\\begin{matrix}a&b\\\\c&d\\end{matrix}', kw: 'matrix grid', accept: false },
  { cmd: 'begin{cases}', title: 'piecewise cases', preview: '\\begin{cases}a&b\\\\c&d\\end{cases}', kw: 'piecewise brace defined', accept: false },
  { cmd: 'begin{aligned}', title: 'aligned rows', preview: '\\begin{aligned}a&=b\\\\c&=d\\end{aligned}', kw: 'align multiline derivation', accept: false },
  { cmd: 'begin{gathered}', title: 'gathered rows', preview: '\\begin{gathered}a\\\\b\\end{gathered}', kw: 'gather multiline', accept: false },
  { cmd: 'begin{smallmatrix}', title: 'small matrix', preview: '\\begin{smallmatrix}a&b\\\\c&d\\end{smallmatrix}', kw: 'matrix inline', accept: false },
  { cmd: 'begin{array}', title: 'array env', preview: '\\begin{array}{}a&b\\end{array}', kw: 'array table', accept: false },
  { cmd: 'text', title: 'literal text', preview: '\\text{if }', kw: 'text words roman' },
  { cmd: 'mathop', title: 'custom operator name', preview: '\\mathop{tr}', kw: 'operator tr aut hom ker name' },
  { cmd: 'pmod', title: '(mod n)', preview: 'x\\equiv y\\pmod{n}', kw: 'mod modulo congruence' },
  { cmd: 'bmod', title: 'mod (binary)', preview: 'x\\bmod n', kw: 'mod modulo' },
  // Accents / enclosures
  { cmd: 'hat', title: 'hat accent', preview: '\\hat{x}', kw: 'accent' },
  { cmd: 'widehat', title: 'wide hat', preview: '\\widehat{xy}', kw: 'accent' },
  { cmd: 'bar', title: 'overline', preview: '\\overline{x}', kw: 'bar conjugate accent' },
  { cmd: 'overline', title: 'overline', preview: '\\overline{AB}', kw: 'bar conjugate accent' },
  { cmd: 'underline', title: 'underline', preview: '\\underline{x}', kw: 'accent' },
  { cmd: 'vec', title: 'vector arrow', preview: '\\vec{v}', kw: 'accent vector' },
  { cmd: 'tilde', title: 'tilde accent', preview: '\\tilde{x}', kw: 'accent' },
  { cmd: 'widetilde', title: 'wide tilde', preview: '\\widetilde{xy}', kw: 'accent' },
  { cmd: 'dot', title: 'dot accent', preview: '\\dot{x}', kw: 'accent newton derivative' },
  { cmd: 'ddot', title: 'double dot', preview: '\\ddot{x}', kw: 'accent second derivative' },
  { cmd: 'overbrace', title: 'overbrace', preview: '\\overbrace{xy}^{n}', kw: 'brace group' },
  { cmd: 'underbrace', title: 'underbrace', preview: '\\underbrace{xy}_{n}', kw: 'brace group' },
  { cmd: 'cancel', title: 'cancel (strike)', preview: '\\cancel{x}', kw: 'strike through' },
  { cmd: 'langle', title: '⟨ ⟩ angle pair', preview: '\\left\\langle x\\right\\rangle', kw: 'inner product expect angle' },
  { cmd: 'lfloor', title: '⌊ ⌋ floor pair', preview: '\\left\\lfloor x\\right\\rfloor', kw: 'floor' },
  { cmd: 'lceil', title: '⌈ ⌉ ceiling pair', preview: '\\left\\lceil x\\right\\rceil', kw: 'ceiling ceil' },
  { cmd: 'lVert', title: '‖ ‖ norm pair', preview: '\\left\\lVert x\\right\\rVert', kw: 'norm' },
  { cmd: 'vert', title: '| bar (restriction/eval)', preview: 'f|_{S}', kw: 'restriction evaluate bar' },
  { cmd: 'upharpoonright', title: '↾ restriction', preview: 'f\\upharpoonright_{S}', kw: 'restriction harpoon' },
  // Greek
  { cmd: 'alpha', title: 'alpha', preview: '\\alpha', kw: 'greek' },
  { cmd: 'beta', title: 'beta', preview: '\\beta', kw: 'greek' },
  { cmd: 'gamma', title: 'gamma', preview: '\\gamma', kw: 'greek' },
  { cmd: 'delta', title: 'delta', preview: '\\delta', kw: 'greek' },
  { cmd: 'Delta', title: 'Delta (cap)', preview: '\\Delta', kw: 'greek' },
  { cmd: 'epsilon', title: 'epsilon', preview: '\\epsilon', kw: 'greek' },
  { cmd: 'varepsilon', title: 'varepsilon', preview: '\\varepsilon', kw: 'greek' },
  { cmd: 'zeta', title: 'zeta', preview: '\\zeta', kw: 'greek' },
  { cmd: 'eta', title: 'eta', preview: '\\eta', kw: 'greek' },
  { cmd: 'theta', title: 'theta', preview: '\\theta', kw: 'greek angle' },
  { cmd: 'vartheta', title: 'vartheta', preview: '\\vartheta', kw: 'greek' },
  { cmd: 'Theta', title: 'Theta (cap)', preview: '\\Theta', kw: 'greek' },
  { cmd: 'iota', title: 'iota', preview: '\\iota', kw: 'greek' },
  { cmd: 'kappa', title: 'kappa', preview: '\\kappa', kw: 'greek' },
  { cmd: 'lambda', title: 'lambda', preview: '\\lambda', kw: 'greek eigenvalue' },
  { cmd: 'Lambda', title: 'Lambda (cap)', preview: '\\Lambda', kw: 'greek' },
  { cmd: 'mu', title: 'mu', preview: '\\mu', kw: 'greek' },
  { cmd: 'nu', title: 'nu', preview: '\\nu', kw: 'greek' },
  { cmd: 'xi', title: 'xi', preview: '\\xi', kw: 'greek' },
  { cmd: 'Xi', title: 'Xi (cap)', preview: '\\Xi', kw: 'greek' },
  { cmd: 'pi', title: 'pi', preview: '\\pi', kw: 'greek' },
  { cmd: 'Pi', title: 'Pi (cap)', preview: '\\Pi', kw: 'greek' },
  { cmd: 'rho', title: 'rho', preview: '\\rho', kw: 'greek' },
  { cmd: 'sigma', title: 'sigma', preview: '\\sigma', kw: 'greek' },
  { cmd: 'Sigma', title: 'Sigma (cap)', preview: '\\Sigma', kw: 'greek' },
  { cmd: 'tau', title: 'tau', preview: '\\tau', kw: 'greek' },
  { cmd: 'upsilon', title: 'upsilon', preview: '\\upsilon', kw: 'greek' },
  { cmd: 'phi', title: 'phi', preview: '\\phi', kw: 'greek' },
  { cmd: 'varphi', title: 'varphi', preview: '\\varphi', kw: 'greek' },
  { cmd: 'Phi', title: 'Phi (cap)', preview: '\\Phi', kw: 'greek' },
  { cmd: 'chi', title: 'chi', preview: '\\chi', kw: 'greek' },
  { cmd: 'psi', title: 'psi', preview: '\\psi', kw: 'greek' },
  { cmd: 'Psi', title: 'Psi (cap)', preview: '\\Psi', kw: 'greek' },
  { cmd: 'omega', title: 'omega', preview: '\\omega', kw: 'greek' },
  { cmd: 'Omega', title: 'Omega (cap)', preview: '\\Omega', kw: 'greek' },
  // Named functions
  { cmd: 'sin', title: 'sin', preview: '\\sin', kw: 'function trig' },
  { cmd: 'cos', title: 'cos', preview: '\\cos', kw: 'function trig' },
  { cmd: 'tan', title: 'tan', preview: '\\tan', kw: 'function trig' },
  { cmd: 'sec', title: 'sec', preview: '\\sec', kw: 'function trig' },
  { cmd: 'csc', title: 'csc', preview: '\\csc', kw: 'function trig' },
  { cmd: 'cot', title: 'cot', preview: '\\cot', kw: 'function trig' },
  { cmd: 'arcsin', title: 'arcsin', preview: '\\arcsin', kw: 'function inverse trig' },
  { cmd: 'arccos', title: 'arccos', preview: '\\arccos', kw: 'function inverse trig' },
  { cmd: 'arctan', title: 'arctan', preview: '\\arctan', kw: 'function inverse trig' },
  { cmd: 'sinh', title: 'sinh', preview: '\\sinh', kw: 'function hyperbolic' },
  { cmd: 'cosh', title: 'cosh', preview: '\\cosh', kw: 'function hyperbolic' },
  { cmd: 'tanh', title: 'tanh', preview: '\\tanh', kw: 'function hyperbolic' },
  { cmd: 'ln', title: 'ln', preview: '\\ln', kw: 'function log' },
  { cmd: 'log', title: 'log', preview: '\\log', kw: 'function' },
  { cmd: 'exp', title: 'exp', preview: '\\exp', kw: 'function' },
  { cmd: 'det', title: 'det', preview: '\\det', kw: 'determinant' },
  { cmd: 'dim', title: 'dim', preview: '\\dim', kw: 'dimension' },
  { cmd: 'ker', title: 'ker', preview: '\\ker', kw: 'kernel null' },
  { cmd: 'gcd', title: 'gcd', preview: '\\gcd', kw: 'greatest divisor' },
  { cmd: 'lcm', title: 'lcm', preview: '\\lcm', kw: 'least multiple' },
  { cmd: 'hom', title: 'hom', preview: '\\hom', kw: 'homomorphism' },
  { cmd: 'deg', title: 'deg', preview: '\\deg', kw: 'degree' },
  { cmd: 'arg', title: 'arg', preview: '\\arg', kw: 'argument' },
  { cmd: 'min', title: 'min', preview: '\\min', kw: 'minimum' },
  { cmd: 'max', title: 'max', preview: '\\max', kw: 'maximum' },
  { cmd: 'sup', title: 'sup', preview: '\\sup', kw: 'supremum' },
  { cmd: 'inf', title: 'inf', preview: '\\inf', kw: 'infimum' },
  { cmd: 'proj', title: 'proj', preview: '\\proj', kw: 'projection' },
  { cmd: 'span', title: 'span', preview: '\\span', kw: 'linear span' },
  { cmd: 'Pr', title: 'Pr', preview: '\\Pr', kw: 'probability' },
  // Relations & operators
  { cmd: 'pm', title: 'plus-minus', preview: '\\pm', kw: 'plus minus' },
  { cmd: 'mp', title: 'minus-plus', preview: '\\mp', kw: 'minus plus' },
  { cmd: 'times', title: 'times', preview: '\\times', kw: 'cross multiply' },
  { cmd: 'div', title: 'divide', preview: '\\div', kw: 'divide' },
  { cmd: 'cdot', title: 'cdot', preview: '\\cdot', kw: 'dot multiply' },
  { cmd: 'circ', title: 'composition', preview: 'f\\circ g', kw: 'compose' },
  { cmd: 'bullet', title: 'bullet', preview: '\\bullet', kw: 'dot' },
  { cmd: 'oplus', title: 'oplus', preview: '\\oplus', kw: 'direct sum circle xor' },
  { cmd: 'otimes', title: 'otimes', preview: '\\otimes', kw: 'tensor circle' },
  { cmd: 'ominus', title: 'ominus', preview: '\\ominus', kw: 'circle' },
  { cmd: 'ast', title: 'asterisk', preview: '\\ast', kw: 'star' },
  { cmd: 'star', title: 'star', preview: '\\star', kw: '' },
  { cmd: 'leq', title: 'less or equal', preview: '\\leq', kw: 'le less' },
  { cmd: 'geq', title: 'greater or equal', preview: '\\geq', kw: 'ge greater' },
  { cmd: 'neq', title: 'not equal', preview: '\\neq', kw: 'not' },
  { cmd: 'approx', title: 'approximately', preview: '\\approx', kw: 'about' },
  { cmd: 'approxeq', title: 'approxeq', preview: '\\approxeq', kw: 'approximately' },
  { cmd: 'simeq', title: 'asymptotically equal', preview: '\\simeq', kw: 'similar' },
  { cmd: 'sim', title: 'similar', preview: '\\sim', kw: 'asymptotic' },
  { cmd: 'cong', title: 'congruent', preview: '\\cong', kw: 'congruence mod' },
  { cmd: 'equiv', title: 'equivalent', preview: '\\equiv', kw: 'identical congruent' },
  { cmd: 'propto', title: 'proportional', preview: '\\propto', kw: 'proportional' },
  { cmd: 'll', title: 'much less', preview: '\\ll', kw: 'much' },
  { cmd: 'gg', title: 'much greater', preview: '\\gg', kw: 'much' },
  { cmd: 'lesssim', title: 'lesssim', preview: '\\lesssim', kw: 'less similar' },
  { cmd: 'gtrsim', title: 'gtrsim', preview: '\\gtrsim', kw: 'greater similar' },
  { cmd: 'prec', title: 'precedes', preview: '\\prec', kw: 'order' },
  { cmd: 'succ', title: 'succeeds', preview: '\\succ', kw: 'order' },
  { cmd: 'preceq', title: 'precedes or equal', preview: '\\preceq', kw: 'order' },
  { cmd: 'succeq', title: 'succeeds or equal', preview: '\\succeq', kw: 'order' },
  { cmd: 'nprec', title: 'not precedes', preview: '\\nprec', kw: 'order not' },
  { cmd: 'nsucc', title: 'not succeeds', preview: '\\nsucc', kw: 'order not' },
  { cmd: 'perp', title: 'perpendicular', preview: '\\perp', kw: 'orthogonal' },
  { cmd: 'parallel', title: 'parallel', preview: '\\parallel', kw: '' },
  { cmd: 'mid', title: 'divides / such that', preview: 'a\\mid b', kw: 'divides bar' },
  { cmd: 'nmid', title: 'does not divide', preview: 'a\\nmid b', kw: 'divides not' },
  { cmd: 'triangleq', title: 'defined as', preview: 'x\\triangleq y', kw: 'define equal' },
  { cmd: 'coloneqq', title: ':= assign', preview: 'x\\coloneqq y', kw: 'assign define equal' },
  // Sets & logic
  { cmd: 'in', title: 'element of', preview: 'x\\in S', kw: 'member set' },
  { cmd: 'ni', title: 'contains', preview: 'S\\ni x', kw: 'member set' },
  { cmd: 'notin', title: 'not element of', preview: 'x\\notin S', kw: 'member set not' },
  { cmd: 'subset', title: 'subset', preview: 'A\\subset B', kw: 'set' },
  { cmd: 'supset', title: 'superset', preview: 'A\\supset B', kw: 'set' },
  { cmd: 'subseteq', title: 'subset or equal', preview: 'A\\subseteq B', kw: 'set' },
  { cmd: 'supseteq', title: 'superset or equal', preview: 'A\\supseteq B', kw: 'set' },
  { cmd: 'subsetneq', title: 'proper subset', preview: 'A\\subsetneq B', kw: 'set' },
  { cmd: 'nsubseteq', title: 'not subset', preview: 'A\\nsubseteq B', kw: 'set not' },
  { cmd: 'cup', title: 'union', preview: 'A\\cup B', kw: 'set' },
  { cmd: 'cap', title: 'intersection', preview: 'A\\cap B', kw: 'set' },
  { cmd: 'setminus', title: 'set difference', preview: 'A\\setminus B', kw: 'set minus' },
  { cmd: 'smallsetminus', title: 'small set minus', preview: 'A\\smallsetminus B', kw: 'set' },
  { cmd: 'varnothing', title: 'empty set', preview: '\\varnothing', kw: 'empty set null' },
  { cmd: 'complement', title: 'complement', preview: 'A^{\\complement}', kw: 'set' },
  { cmd: 'forall', title: 'for all', preview: '\\forall x', kw: 'quantifier' },
  { cmd: 'exists', title: 'exists', preview: '\\exists x', kw: 'quantifier' },
  { cmd: 'nexists', title: 'does not exist', preview: '\\nexists', kw: 'quantifier not' },
  { cmd: 'neg', title: 'not', preview: '\\neg p', kw: 'not logic' },
  { cmd: 'land', title: 'and', preview: 'p\\land q', kw: 'wedge logic' },
  { cmd: 'lor', title: 'or', preview: 'p\\lor q', kw: 'vee logic' },
  { cmd: 'models', title: 'models', preview: 'T\\models\\phi', kw: 'logic entail' },
  { cmd: 'vdash', title: 'proves', preview: 'T\\vdash\\phi', kw: 'turnstile prove' },
  { cmd: 'vDash', title: 'entails', preview: 'T\\vDash\\phi', kw: 'double turnstile' },
  { cmd: 'nvdash', title: 'does not prove', preview: 'T\\nvdash\\phi', kw: 'not prove' },
  { cmd: 'top', title: 'top / true', preview: '\\top', kw: 'true lattice' },
  { cmd: 'bot', title: 'bottom / false', preview: '\\bot', kw: 'false lattice' },
  // Arrows
  { cmd: 'to', title: 'to arrow', preview: 'x\\to0', kw: 'right arrow' },
  { cmd: 'rightarrow', title: 'right arrow', preview: '\\rightarrow', kw: 'to' },
  { cmd: 'leftarrow', title: 'left arrow', preview: '\\leftarrow', kw: 'from' },
  { cmd: 'leftrightarrow', title: 'left-right arrow', preview: '\\leftrightarrow', kw: 'bi' },
  { cmd: 'Rightarrow', title: 'double right arrow', preview: '\\Rightarrow', kw: 'implies' },
  { cmd: 'Leftarrow', title: 'double left arrow', preview: '\\Leftarrow', kw: 'implied' },
  { cmd: 'Leftrightarrow', title: 'double both arrow', preview: '\\Leftrightarrow', kw: 'iff' },
  { cmd: 'implies', title: 'implies (long)', preview: '\\implies', kw: 'then' },
  { cmd: 'impliedby', title: 'implied by', preview: '\\impliedby', kw: 'if' },
  { cmd: 'iff', title: 'iff', preview: '\\iff', kw: 'equivalent' },
  { cmd: 'mapsto', title: 'maps to', preview: 'x\\mapsto y', kw: 'function assignment' },
  { cmd: 'longrightarrow', title: 'long right arrow', preview: '\\longrightarrow', kw: 'arrow' },
  { cmd: 'hookrightarrow', title: 'injection arrow', preview: '\\hookrightarrow', kw: 'embed inject' },
  { cmd: 'twoheadrightarrow', title: 'surjection arrow', preview: '\\twoheadrightarrow', kw: 'onto surject' },
  { cmd: 'rightarrowtail', title: 'tail arrow', preview: '\\rightarrowtail', kw: 'inject' },
  { cmd: 'rightsquigarrow', title: 'squiggle arrow', preview: '\\rightsquigarrow', kw: 'lead' },
  { cmd: 'rightleftharpoons', title: 'equilibrium harpoons', preview: '\\rightleftharpoons', kw: 'reaction' },
  { cmd: 'xrightarrow', title: 'labeled arrow', preview: '\\xrightarrow{f}', kw: 'arrow label over', accept: false },
  { cmd: 'xleftarrow', title: 'labeled left arrow', preview: '\\xleftarrow{f}', kw: 'arrow label', accept: false },
  { cmd: 'uparrow', title: 'up arrow', preview: '\\uparrow', kw: '' },
  { cmd: 'downarrow', title: 'down arrow', preview: '\\downarrow', kw: '' },
  { cmd: 'nearrow', title: 'ne arrow', preview: '\\nearrow', kw: '' },
  { cmd: 'searrow', title: 'se arrow', preview: '\\searrow', kw: '' },
  // Misc symbols
  { cmd: 'infty', title: 'infinity', preview: '\\infty', kw: 'infinite' },
  { cmd: 'partial', title: 'partial derivative', preview: '\\partial', kw: 'del' },
  { cmd: 'nabla', title: 'nabla / grad', preview: '\\nabla', kw: 'gradient del' },
  { cmd: 'aleph', title: 'aleph', preview: '\\aleph', kw: 'cardinality' },
  { cmd: 'beth', title: 'beth', preview: '\\beth', kw: 'cardinality' },
  { cmd: 'hbar', title: 'h-bar', preview: '\\hbar', kw: 'planck' },
  { cmd: 'hslash', title: 'h-slash', preview: '\\hslash', kw: 'planck' },
  { cmd: 'ell', title: 'script l', preview: '\\ell', kw: 'l' },
  { cmd: 'Re', title: 'real part', preview: '\\Re', kw: 'fraktur' },
  { cmd: 'Im', title: 'imaginary part', preview: '\\Im', kw: 'fraktur' },
  { cmd: 'wp', title: 'weierstrass p', preview: '\\wp', kw: 'fraktur' },
  { cmd: 'imath', title: 'dotless i', preview: '\\imath', kw: '' },
  { cmd: 'jmath', title: 'dotless j', preview: '\\jmath', kw: '' },
  { cmd: 'angle', title: 'angle', preview: '\\angle', kw: '' },
  { cmd: 'measuredangle', title: 'measured angle', preview: '\\measuredangle', kw: '' },
  { cmd: 'triangle', title: 'triangle', preview: '\\triangle', kw: '' },
  { cmd: 'square', title: 'square', preview: '\\square', kw: 'qed' },
  { cmd: 'dag', title: 'dagger', preview: '\\dag', kw: 'dagger' },
  { cmd: 'ddag', title: 'double dagger', preview: '\\ddag', kw: 'dagger' },
  { cmd: 'checkmark', title: 'check', preview: '\\checkmark', kw: 'tick' },
  { cmd: 'ldots', title: 'dots (low)', preview: 'a_1,\\ldots,a_n', kw: 'ellipsis' },
  { cmd: 'cdots', title: 'dots (center)', preview: 'a+\\cdots+z', kw: 'ellipsis' },
  { cmd: 'vdots', title: 'vertical dots', preview: '\\vdots', kw: 'ellipsis' },
  { cmd: 'ddots', title: 'diagonal dots', preview: '\\ddots', kw: 'ellipsis' },
  { cmd: 'hdots', title: 'horizontal dots', preview: 'a_1,\\hdots,a_n', kw: 'ellipsis' },
  { cmd: 'prime', title: 'prime', preview: "f'", kw: 'derivative tick' },
  { cmd: 'backprime', title: 'back prime', preview: '\\backprime', kw: '' },
  // Fonts (work via \… command input)
  { cmd: 'mathrm', title: 'roman (upright)', preview: '\\mathrm{d}x', kw: 'font upright roman' },
  { cmd: 'mathbf', title: 'bold', preview: '\\mathbf{v}', kw: 'font bold' },
  { cmd: 'boldsymbol', title: 'bold symbol', preview: '\\boldsymbol{\\alpha}', kw: 'font bold' },
  { cmd: 'mathcal', title: 'calligraphic', preview: '\\mathcal{L}', kw: 'font cal script' },
  { cmd: 'mathscr', title: 'script', preview: '\\mathscr{F}', kw: 'font script' },
  { cmd: 'mathfrak', title: 'fraktur', preview: '\\mathfrak{g}', kw: 'font fraktur gothic' },
  { cmd: 'stackrel', title: 'stack relation', preview: 'x\\stackrel{?}{=}y', kw: 'overset above' },
];
